title: Traveller | practice
locale: en_US
baseurl: https://Traveller00007/traveller00007.github.io
url: https://Traveller00007/traveller00007.github.io
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
sass: 
  sass_dir: _sass
gems:
  - jekyll-sitemap
  - jekyll-glist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_codearay: false

post_ext: post
page_ext: page

post_layout: post
page_layout: page

titlecase: true
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

  
